-- AlterTable
ALTER TABLE "Hotels" ALTER COLUMN "costPerNight" SET DATA TYPE TEXT,
ALTER COLUMN "availableRooms" SET DATA TYPE TEXT,
ALTER COLUMN "rating" DROP DEFAULT,
ALTER COLUMN "rating" SET DATA TYPE TEXT;
